#server.port 자동완성 사용.
server:
  port: 10000

### JDBC
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/spring?serverTimezone=Asia/Seoul
#    username: root
#    password: 1234


### Hikari CP
spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/spring?serverTimezone=Asia/Seoul #spring은 DB이름이다. DBeaver에서 create랑 use하는 이름
      username: root
      password: 1234